<?php
declare(strict_types=1);
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/permissions.php';
$user=hippo_require_login_page();$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!isset($_POST['csrf_token'])||!hash_equals(hippo_csrf_token(),(string)$_POST['csrf_token']))$error='درخواست معتبر نیست. صفحه را تازه‌سازی کنید.';
  else{$p=(string)($_POST['password']??'');$c=(string)($_POST['confirm']??'');if(mb_strlen($p)<10)$error='رمز جدید باید حداقل ۱۰ کاراکتر باشد.';elseif($p!==$c)$error='تکرار رمز با رمز جدید یکسان نیست.';else{$pdo=hippo_db();$stmt=$pdo->prepare('UPDATE users SET password_hash=?,password_changed_at=CURRENT_TIMESTAMP,must_change_password=0,failed_attempts=0,locked_until=NULL WHERE id=?');$stmt->execute([password_hash($p,PASSWORD_DEFAULT),(int)$user['id']]);$row=hippo_fetch_current_db_user($pdo,(int)$user['id']);$_SESSION['password_changed_at']=(string)($row['password_changed_at']??'');hippo_audit($pdo,(int)$user['id'],'password_change','user',(string)$user['id']);header('Location: '.(hippo_role_alias($user['role'])==='manager_viewer'?'manager.php':'index.php'));exit;}}
}
?><!DOCTYPE html><html lang="fa" dir="rtl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>تغییر رمز عبور</title><link rel="stylesheet" href="assets/css/tokens.css"><link rel="stylesheet" href="assets/css/base.css"><link rel="stylesheet" href="assets/css/components.css"><link rel="stylesheet" href="assets/css/v05-rbac.css"><?php require __DIR__ . '/pwa_head.php'; ?></head><body class="v05-simple-page"><form class="v05-password-card" method="post"><h1>تغییر رمز عبور</h1><p>برای ادامه، یک رمز اختصاصی با حداقل ۱۰ کاراکتر انتخاب کنید.</p><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(hippo_csrf_token(),ENT_QUOTES,'UTF-8')?>"><div class="field"><label>رمز جدید</label><input type="password" name="password" required autocomplete="new-password"></div><div class="field"><label>تکرار رمز جدید</label><input type="password" name="confirm" required autocomplete="new-password"></div><?php if($error):?><div class="alert danger"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?><button class="btn primary" type="submit">ثبت رمز جدید</button></form></body></html>
