<?php
declare(strict_types=1);
require_once __DIR__ . '/auth.php';
$user = hippo_require_login_page();
function pi_e(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
$publicUser = ['name'=>$user['display_name'],'role'=>$user['role_label'],'username'=>$user['username']];
?>
<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ثبت ایراد پایلوت | دستیار فروش</title>
<link rel="stylesheet" href="assets/css/tokens.css"><link rel="stylesheet" href="assets/css/base.css"><link rel="stylesheet" href="assets/css/components.css"><link rel="stylesheet" href="assets/css/layout.css"><link rel="stylesheet" href="assets/css/pages.css"><link rel="stylesheet" href="assets/css/responsive.css"><link rel="stylesheet" href="assets/css/v07-ariana.css"><?php require __DIR__.'/pwa_head.php'; ?>
<style>.pi-wrap{max-width:1050px;margin:auto;padding:22px}.pi-head{display:flex;justify-content:space-between;gap:16px;align-items:center}.pi-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.pi-card{background:#fff;border:1px solid #e8e4f4;border-radius:20px;padding:18px}.pi-card textarea{min-height:96px}.pi-list{display:grid;gap:10px;margin-top:14px}.pi-item{border:1px solid #ece9f5;border-radius:16px;padding:14px;background:#fff}.pi-meta{display:flex;gap:8px;flex-wrap:wrap;color:#6b647d;font-size:12px}.pi-actions{display:flex;gap:8px;flex-wrap:wrap}.pi-empty{text-align:center;padding:34px;color:#6b647d}@media(max-width:760px){.pi-head{align-items:flex-start;flex-direction:column}.pi-grid{grid-template-columns:1fr}.pi-actions .btn{flex:1}}</style></head><body class="v07-ui"><main class="pi-wrap"><header class="pi-head"><div><small>دفترچه یک‌ماهه پایلوت</small><h1>ثبت ایراد و تجربه واقعی</h1><p>اطلاعات فقط در همین مرورگر ذخیره می‌شود و با خروجی JSON/CSV قابل ارسال است.</p></div><div class="pi-actions"><a class="btn" href="index.php">بازگشت</a><button class="btn soft" onclick="exportJson()">خروجی JSON</button><button class="btn soft" onclick="exportCsv()">خروجی CSV</button></div></header>
<section class="pi-card" style="margin-top:18px"><form id="issueForm"><div class="pi-grid"><div class="field"><label>صفحه</label><input id="page" required placeholder="مثلاً مشتریان یا ثبت مذاکره"></div><div class="field"><label>شدت</label><select id="severity"><option value="critical">بحرانی</option><option value="high">زیاد</option><option value="medium" selected>متوسط</option><option value="low">کم</option><option value="idea">پیشنهاد</option></select></div><div class="field"><label>کاری که انجام دادی</label><textarea id="steps" required></textarea></div><div class="field"><label>چیزی که واقعاً رخ داد</label><textarea id="actual" required></textarea></div><div class="field"><label>نتیجه مورد انتظار</label><textarea id="expected"></textarea></div><div class="field"><label>یادداشت تصویر یا شرایط</label><textarea id="evidence" placeholder="مثلاً گوشی سامسونگ، اینترنت همراه، تصویر جدا ارسال شد"></textarea></div></div><div class="pi-actions" style="margin-top:14px"><button class="btn primary" type="submit">ثبت ایراد</button><button class="btn" type="reset">پاک‌کردن فرم</button><button class="btn danger" type="button" onclick="clearAll()">حذف همه گزارش‌های این مرورگر</button></div></form></section>
<section class="pi-list" id="issueList"></section></main>
<script>window.PILOT_USER=<?=json_encode($publicUser,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script>
<script>
(()=>{'use strict';const KEY='hippoPilot:user:'+String(window.PILOT_USER.username||'unknown')+':issues:v09';const $=id=>document.getElementById(id);const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}};const write=x=>localStorage.setItem(KEY,JSON.stringify(x));const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));function render(){const items=read();$('issueList').innerHTML=items.length?items.slice().reverse().map(x=>`<article class="pi-item"><div class="pi-meta"><b>${esc(x.severity)}</b><span>${esc(x.page)}</span><span>${esc(x.user.name)} · ${esc(x.user.role)}</span><span>${new Date(x.createdAt).toLocaleString('fa-IR')}</span></div><h3>${esc(x.actual).slice(0,140)}</h3><details><summary>جزئیات</summary><p><b>مراحل:</b> ${esc(x.steps)}</p><p><b>انتظار:</b> ${esc(x.expected||'—')}</p><p><b>مدرک:</b> ${esc(x.evidence||'—')}</p></details><button class="btn small danger" onclick="removeIssue('${esc(x.id)}')">حذف</button></article>`).join(''):'<div class="pi-card pi-empty">هنوز ایرادی ثبت نشده است.</div>'}window.removeIssue=id=>{write(read().filter(x=>x.id!==id));render()};window.clearAll=()=>{if(confirm('همه گزارش‌های این مرورگر حذف شوند؟')){localStorage.removeItem(KEY);render()}};function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}window.exportJson=()=>download('pilot-issues-v09.json',JSON.stringify(read(),null,2),'application/json');window.exportCsv=()=>{const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const rows=[['id','createdAt','user','role','page','severity','steps','expected','actual','evidence'],...read().map(x=>[x.id,x.createdAt,x.user.name,x.user.role,x.page,x.severity,x.steps,x.expected,x.actual,x.evidence])];download('pilot-issues-v09.csv','\ufeff'+rows.map(r=>r.map(q).join(',')).join('\n'),'text/csv;charset=utf-8')};$('issueForm').addEventListener('submit',e=>{e.preventDefault();const items=read();items.push({id:'i'+Date.now(),createdAt:new Date().toISOString(),user:window.PILOT_USER,page:$('page').value.trim(),severity:$('severity').value,steps:$('steps').value.trim(),expected:$('expected').value.trim(),actual:$('actual').value.trim(),evidence:$('evidence').value.trim()});write(items);e.target.reset();render();alert('گزارش در همین مرورگر ثبت شد')});render()})();
</script></body></html>
